"""The interface every lending back end implements (Fineract in production, demo data in development)."""

from __future__ import annotations

from datetime import date
from typing import Protocol

from ..domain.models import (
    ActionResult,
    ApplicationIn,
    ApproveIn,
    Assessment,
    Borrower,
    BorrowerDocument,
    BorrowerIn,
    BorrowerListItem,
    CollectionItem,
    Dashboard,
    DisburseIn,
    LoanDetail,
    LoanEvent,
    LoanReview,
    LoanSummary,
    PortalApplicationIn,
    Receipt,
    RejectIn,
    RepaymentIn,
    StaffUser,
)


class BackendError(Exception):
    """A problem the user can act on. `status` maps to the HTTP status returned."""

    def __init__(self, message: str, status: int = 400):
        super().__init__(message)
        self.message = message
        self.status = status


class NotFound(BackendError):
    def __init__(self, what: str):
        super().__init__(f"{what} was not found.", 404)


class AuthFailed(BackendError):
    def __init__(self, message: str = "Username or password is wrong."):
        super().__init__(message, 401)


class LendingBackend(Protocol):
    # Staff calls take `cred`: the signed-in staff member's Fineract credential (ignored by the demo).
    async def authenticate(self, username: str, password: str) -> tuple[StaffUser, str]: ...
    async def dashboard(self, cred: str, today: date) -> Dashboard: ...
    async def list_loans(self, cred: str, today: date, states: set[str] | None = None) -> list[LoanSummary]: ...
    async def get_loan(self, cred: str, loan_id: int, today: date) -> LoanDetail: ...
    async def save_assessment(self, cred: str, loan_id: int, assessment: Assessment) -> None: ...
    async def approve(self, cred: str, loan_id: int, body: ApproveIn, today: date) -> ActionResult: ...
    async def reject(self, cred: str, loan_id: int, body: RejectIn, today: date) -> ActionResult: ...
    async def disburse(self, cred: str, loan_id: int, body: DisburseIn, today: date) -> ActionResult: ...
    async def add_loan_note(self, cred: str, loan_id: int, text: str, today: date) -> None: ...
    async def list_loan_documents(self, cred: str, loan_id: int) -> list[BorrowerDocument]: ...
    async def add_loan_document(
        self, cred: str, loan_id: int, kind: str, file_name: str, content_type: str, data: bytes, today: date
    ) -> BorrowerDocument: ...
    async def get_loan_document(self, cred: str, loan_id: int, doc_id: int) -> tuple[BorrowerDocument, bytes]: ...
    async def collections(self, cred: str, today: date) -> list[CollectionItem]: ...
    async def record_repayment(self, cred: str, loan_id: int, body: RepaymentIn, today: date) -> Receipt: ...

    # Borrowers and KYC documents (staff).
    async def search_borrowers(self, cred: str, query: str, limit: int = 50) -> list[BorrowerListItem]: ...
    async def get_borrower(self, cred: str, borrower_id: int) -> Borrower: ...
    async def create_borrower(self, cred: str, body: BorrowerIn, today: date) -> Borrower: ...
    async def update_borrower(self, cred: str, borrower_id: int, body: BorrowerIn) -> Borrower: ...
    async def borrower_loan_list(self, cred: str, borrower_id: int, today: date) -> list[LoanSummary]: ...
    async def list_documents(self, cred: str, borrower_id: int) -> list[BorrowerDocument]: ...
    async def add_document(
        self, cred: str, borrower_id: int, kind: str, file_name: str, content_type: str, data: bytes, today: date
    ) -> BorrowerDocument: ...
    async def get_document(self, cred: str, borrower_id: int, doc_id: int) -> tuple[BorrowerDocument, bytes]: ...
    async def delete_document(self, cred: str, borrower_id: int, doc_id: int) -> None: ...
    async def delete_loan_document(self, cred: str, loan_id: int, doc_id: int) -> None: ...
    async def add_client_note(self, cred: str, borrower_id: int, text: str, today: date) -> None: ...
    async def client_notes(self, cred: str, borrower_id: int) -> list[LoanEvent]: ...
    async def save_review(self, cred: str, loan_id: int, review: LoanReview) -> None: ...
    async def set_photo(self, cred: str, borrower_id: int, jpeg: bytes) -> None: ...
    async def get_photo(self, cred: str, borrower_id: int) -> bytes | None: ...
    async def create_application(
        self, cred: str, borrower_id: int, body: ApplicationIn, today: date
    ) -> LoanSummary: ...

    # Borrower portal calls run as the portal's technical account.
    async def find_borrower_by_phone(self, phone: str) -> Borrower | None: ...
    async def borrower_loans(self, borrower_id: int, today: date) -> list[LoanDetail]: ...
    async def submit_application(self, borrower_id: int, body: PortalApplicationIn, today: date) -> LoanSummary: ...
    async def aclose(self) -> None: ...


def normalise_phone(phone: str) -> str:
    """PNG mobile numbers as 8 digits: '+675 7123 4567', '675-71234567', '7123 4567' -> '71234567'."""
    digits = "".join(c for c in phone if c.isdigit())
    if digits.startswith("675") and len(digits) == 11:
        digits = digits[3:]
    return digits
